apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensensor-ingress
  namespace: whitewhale
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "12m"
    nginx.org/client-max-body-size: "12m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
          - opensensor.io
          - www.opensensor.io
          - api.opensensor.io
          - growmax.opensensor.io
          - solar.opensensor.io
          - solar-api.opensensor.io
      secretName: letsencrypt-prod
  rules:
  - host: opensensor.io
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opensensor-growmax
              port:
                number: 80
  - host: www.opensensor.io
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opensensor-growmax
              port:
                number: 80
  - host: api.opensensor.io
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opensensor-api
              port:
                number: 80
  - host: growmax.opensensor.io
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opensensor-growmax
              port:
                number: 80
  - host: solar.opensensor.io
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opensensor-solar
              port:
                number: 80
  - host: solar-api.opensensor.io
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opensensor-solar-api
              port:
                number: 80
