# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_codebase:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DigitalOcean-PROD

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: |
          python -m pip install pre-commit
          pre-commit run --all-files --verbose --show-diff-on-failure

  build_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DigitalOcean-PROD
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Run Docker Build; main Publishes Image to Container Registry
        uses: ./.github/workflows/build_api
        with:
          dockerfile: ./Dockerfile
          image_path: whitewhale/opensensor
